apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wangpanbot
  namespace: wangpanbot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bot.example.com
      secretName: wangpanbot-tls
  rules:
    - host: bot.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wangpanbot
                port:
                  number: 80
